const process = require("process");
const builtins = require("builtin-modules");
const fs = require('fs');

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.env.BUILD === "production";

const renamePlugin = {
	name: "rename-styles",
	setup(build) {
		build.onEnd(() => {
			const { outfile } = build.initialOptions;
			const outcss = outfile.replace(/\.js$/, ".css");
			const fixcss = outfile.replace(/main\.js$/, "styles.css");
			if (fs.existsSync(outcss)) {
				console.log("Renaming", outcss, "to", fixcss);
				fs.renameSync(outcss, fixcss);
			}
		});
	},
};

module.exports = {
	banner: {
		js: banner,
	},
	bundle: true,
	external: ["obsidian", "electron", ...builtins],
	format: "cjs",
	target: "es2016",
	logLevel: "info",
	sourcemap: isProd ? false : "inline",
	treeShaking: true,
	plugins: [renamePlugin],
};
